accepted = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "ISC",
    "MPL-2.0",
    "BSD-3-Clause",
    "OpenSSL"
]

workarounds = [
    "rustls",
]

[webpki.clarify]
license = "ISC"

[rustls-webpki.clarify]
license = "ISC"

[webpki-roots.clarify]
license = "MPL-2.0"

[[webpki.clarify.files]]
path = 'LICENSE'
license = 'ISC'
checksum = '5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a'

[[rustls-webpki.clarify.files]]
path = 'LICENSE'
checksum = '5b698ca13897be3afdb7174256fa1574f8c6892b8bea1a66dd6469d3fe27885a'

[[webpki-roots.clarify.files]]
path = 'LICENSE'
checksum = '6a70a4bf6b010016d59a64b8ae4ad8dc7f5ef16f1fb453cc2ecd771c5a341131'

[ring.clarify]
license = "ISC AND MIT AND OpenSSL"

[[ring.clarify.files]]
path = 'LICENSE'
checksum = '76b39f9b371688eac9d8323f96ee80b3aef5ecbc2217f25377bd4e4a615296a9'